title: willearning
url: "" 
author: willy chang

plugins:
  - jekyll-feed
  - jekyll-paginate

permalink : /:year/:month/:day/:title/
paginate : 10

exclude : ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge
markdown: kramdown
mathjax: true