# Site settings
name: Willearning
email: willychang17@gmail.com
author: willy chang
url: https://willylearning.nctu.me/
resume_site: https://willylearning.nctu.me/
github: https://github.com/willychang21/
baseurl: 
description: We lost because we told ourselves we lost.
meta_description: The minute you start talking about what you’re going to do if you lose, you have lost.
motto: It's our wits that make us men.
banner: No one can make you feel inferior without your consent.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: willychang21

# Build settings
markdown: kramdown



